#!/bin/sh

cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P0_five.fq P0.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P100_five.fq P100.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P101_five.fq P101.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P102_five.fq P102.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P103_five.fq P103.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P104_five.fq P104.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P105_five.fq P105.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P106_five.fq P106.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P107_five.fq P107.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P108_five.fq P108.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P109_five.fq P109.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P10_five.fq P10.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P110_five.fq P110.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P111_five.fq P111.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P112_five.fq P112.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P113_five.fq P113.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P114_five.fq P114.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P115_five.fq P115.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P116_five.fq P116.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P117_five.fq P117.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P118_five.fq P118.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P119_five.fq P119.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P11_five.fq P11.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P120_five.fq P120.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P121_five.fq P121.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P122_five.fq P122.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P123_five.fq P123.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P124_five.fq P124.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P125_five.fq P125.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P126_five.fq P126.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P127_five.fq P127.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P128_five.fq P128.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P129_five.fq P129.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P12_five.fq P12.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P130_five.fq P130.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P131_five.fq P131.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P132_five.fq P132.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P133_five.fq P133.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P134_five.fq P134.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P135_five.fq P135.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P136_five.fq P136.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P137_five.fq P137.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P138_five.fq P138.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P139_five.fq P139.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P13_five.fq P13.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P14_five.fq P14.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P15_five.fq P15.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P16_five.fq P16.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P17_five.fq P17.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P18_five.fq P18.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P19_five.fq P19.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P1_five.fq P1.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P20_five.fq P20.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P21_five.fq P21.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P22_five.fq P22.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P23_five.fq P23.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P24_five.fq P24.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P25_five.fq P25.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P26_five.fq P26.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P27_five.fq P27.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P28_five.fq P28.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P29_five.fq P29.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P2_five.fq P2.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P30_five.fq P30.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P31_five.fq P31.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P32_five.fq P32.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P33_five.fq P33.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P34_five.fq P34.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P35_five.fq P35.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P36_five.fq P36.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P37_five.fq P37.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P38_five.fq P38.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P39_five.fq P39.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P3_five.fq P3.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P40_five.fq P40.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P41_five.fq P41.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P42_five.fq P42.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P43_five.fq P43.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P44_five.fq P44.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P45_five.fq P45.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P46_five.fq P46.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P47_five.fq P47.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P48_five.fq P48.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P49_five.fq P49.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P4_five.fq P4.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P50_five.fq P50.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P51_five.fq P51.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P52_five.fq P52.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P53_five.fq P53.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P54_five.fq P54.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P55_five.fq P55.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P56_five.fq P56.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P57_five.fq P57.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P58_five.fq P58.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P59_five.fq P59.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P5_five.fq P5.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P60_five.fq P60.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P61_five.fq P61.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P62_five.fq P62.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P63_five.fq P63.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P64_five.fq P64.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P65_five.fq P65.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P66_five.fq P66.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P67_five.fq P67.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P68_five.fq P68.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P69_five.fq P69.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P6_five.fq P6.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P70_five.fq P70.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P71_five.fq P71.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P72_five.fq P72.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P73_five.fq P73.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P74_five.fq P74.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P75_five.fq P75.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P76_five.fq P76.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P77_five.fq P77.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P78_five.fq P78.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P79_five.fq P79.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P7_five.fq P7.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P80_five.fq P80.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P81_five.fq P81.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P82_five.fq P82.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P83_five.fq P83.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P84_five.fq P84.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P85_five.fq P85.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P86_five.fq P86.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P87_five.fq P87.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P88_five.fq P88.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P89_five.fq P89.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P8_five.fq P8.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P90_five.fq P90.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P91_five.fq P91.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P92_five.fq P92.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P93_five.fq P93.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P94_five.fq P94.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P95_five.fq P95.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P96_five.fq P96.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P97_five.fq P97.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P98_five.fq P98.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P99_five.fq P99.fastq &
cutadapt -g GTTCAGAGTTCTACAGTCCGACGATC -o P9_five.fq P9.fastq &
