#!/bin/sh

cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P0_three.fq P0_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P100_three.fq P100_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P101_three.fq P101_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P102_three.fq P102_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P103_three.fq P103_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P104_three.fq P104_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P105_three.fq P105_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P106_three.fq P106_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P107_three.fq P107_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P108_three.fq P108_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P109_three.fq P109_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P10_three.fq P10_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P110_three.fq P110_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P111_three.fq P111_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P112_three.fq P112_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P113_three.fq P113_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P114_three.fq P114_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P115_three.fq P115_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P116_three.fq P116_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P117_three.fq P117_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P118_three.fq P118_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P119_three.fq P119_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P11_three.fq P11_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P120_three.fq P120_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P121_three.fq P121_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P122_three.fq P122_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P123_three.fq P123_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P124_three.fq P124_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P125_three.fq P125_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P126_three.fq P126_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P127_three.fq P127_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P128_three.fq P128_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P129_three.fq P129_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P12_three.fq P12_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P130_three.fq P130_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P131_three.fq P131_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P132_three.fq P132_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P133_three.fq P133_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P134_three.fq P134_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P135_three.fq P135_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P136_three.fq P136_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P137_three.fq P137_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P138_three.fq P138_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P139_three.fq P139_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P13_three.fq P13_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P14_three.fq P14_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P15_three.fq P15_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P16_three.fq P16_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P17_three.fq P17_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P18_three.fq P18_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P19_three.fq P19_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P1_three.fq P1_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P20_three.fq P20_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P21_three.fq P21_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P22_three.fq P22_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P23_three.fq P23_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P24_three.fq P24_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P25_three.fq P25_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P26_three.fq P26_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P27_three.fq P27_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P28_three.fq P28_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P29_three.fq P29_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P2_three.fq P2_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P30_three.fq P30_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P31_three.fq P31_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P32_three.fq P32_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P33_three.fq P33_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P34_three.fq P34_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P35_three.fq P35_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P36_three.fq P36_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P37_three.fq P37_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P38_three.fq P38_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P39_three.fq P39_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P3_three.fq P3_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P40_three.fq P40_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P41_three.fq P41_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P42_three.fq P42_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P43_three.fq P43_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P44_three.fq P44_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P45_three.fq P45_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P46_three.fq P46_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P47_three.fq P47_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P48_three.fq P48_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P49_three.fq P49_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P4_three.fq P4_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P50_three.fq P50_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P51_three.fq P51_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P52_three.fq P52_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P53_three.fq P53_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P54_three.fq P54_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P55_three.fq P55_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P56_three.fq P56_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P57_three.fq P57_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P58_three.fq P58_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P59_three.fq P59_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P5_three.fq P5_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P60_three.fq P60_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P61_three.fq P61_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P62_three.fq P62_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P63_three.fq P63_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P64_three.fq P64_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P65_three.fq P65_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P66_three.fq P66_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P67_three.fq P67_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P68_three.fq P68_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P69_three.fq P69_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P6_three.fq P6_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P70_three.fq P70_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P71_three.fq P71_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P72_three.fq P72_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P73_three.fq P73_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P74_three.fq P74_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P75_three.fq P75_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P76_three.fq P76_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P77_three.fq P77_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P78_three.fq P78_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P79_three.fq P79_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P7_three.fq P7_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P80_three.fq P80_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P81_three.fq P81_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P82_three.fq P82_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P83_three.fq P83_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P84_three.fq P84_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P85_three.fq P85_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P86_three.fq P86_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P87_three.fq P87_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P88_three.fq P88_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P89_three.fq P89_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P8_three.fq P8_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P90_three.fq P90_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P91_three.fq P91_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P92_three.fq P92_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P93_three.fq P93_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P94_three.fq P94_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P95_three.fq P95_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P96_three.fq P96_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P97_three.fq P97_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P98_three.fq P98_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P99_three.fq P99_five.fq &
cutadapt -a AACTGTAGGCACCATCAAT -m 15 -o P9_three.fq P9_five.fq &
