#!/usr/bin/perl

use strict;
use warnings;

# Since the micorRNA matrix generated by miRDeep2 has duplicated because of the different precursors, we need to merge.

my $file = shift;
my %hash;

die "\n\tperl $0 <FILE>\n\n" unless $file;
open(FI, $file) or die "Can't open for $!\n";
my $title = <FI>;
while(<FI>){
	chomp;
	my @a = split /\s/;
#	print "$_\n";
	if ( not exists $hash{$a[0]}) {
	$hash{$a[0]} = $_;
#	print "$_\n";
	}
	elsif ( exists $hash{$a[0]} ){
	my @b = split /\s/, $hash{$a[0]};
	my @c = split /\s/;
		for( my $i=1; $i<=$#b; $i++ ) {
			$b[$i]= $b[$i]+$c[$i];
#			print "$b[$i]\n";
		}
	my $new_value = "@b";
	$hash{$b[0]} = $new_value;
#	print "$new_value\n";
	}
}


print "$title";

my $k;
my $v;

while ( ($k,$v) = each %hash) {
	print "$v\n";
}
